# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 532)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vl_graph = QtWidgets.QVBoxLayout()
        self.vl_graph.setObjectName("vl_graph")
        self.verticalLayout_2.addLayout(self.vl_graph)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lw_results = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lw_results.setFont(font)
        self.lw_results.setObjectName("lw_results")
        self.verticalLayout_2.addWidget(self.lw_results)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cb_target_variable = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_target_variable.setFont(font)
        self.cb_target_variable.setObjectName("cb_target_variable")
        self.verticalLayout.addWidget(self.cb_target_variable)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.cb_algorithm = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_algorithm.setFont(font)
        self.cb_algorithm.setCurrentText("")
        self.cb_algorithm.setObjectName("cb_algorithm")
        self.verticalLayout.addWidget(self.cb_algorithm)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.cb_alpha = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_alpha.setFont(font)
        self.cb_alpha.setObjectName("cb_alpha")
        self.verticalLayout.addWidget(self.cb_alpha)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_lnx = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_lnx.setFont(font)
        self.cb_lnx.setObjectName("cb_lnx")
        self.horizontalLayout_2.addWidget(self.cb_lnx)
        self.cb_x2 = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_x2.setFont(font)
        self.cb_x2.setObjectName("cb_x2")
        self.horizontalLayout_2.addWidget(self.cb_x2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cb_1x = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_1x.setFont(font)
        self.cb_1x.setObjectName("cb_1x")
        self.horizontalLayout_3.addWidget(self.cb_1x)
        self.cb_ex = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_ex.setFont(font)
        self.cb_ex.setObjectName("cb_ex")
        self.horizontalLayout_3.addWidget(self.cb_ex)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pb_build_model = QtWidgets.QPushButton(self.centralwidget)
        self.pb_build_model.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_build_model.setFont(font)
        self.pb_build_model.setAutoFillBackground(False)
        self.pb_build_model.setObjectName("pb_build_model")
        self.verticalLayout.addWidget(self.pb_build_model)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_file = QtWidgets.QAction(MainWindow)
        self.action_open_file.setObjectName("action_open_file")
        self.action_export = QtWidgets.QAction(MainWindow)
        self.action_export.setEnabled(False)
        self.action_export.setObjectName("action_export")
        self.action_import = QtWidgets.QAction(MainWindow)
        self.action_import.setObjectName("action_import")
        self.menu.addAction(self.action_open_file)
        self.menu.addSeparator()
        self.menu.addAction(self.action_export)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Набор регрессоров"))
        self.label.setText(_translate("MainWindow", "Целевая переменная"))
        self.label_2.setText(_translate("MainWindow", "Алгоритм построения модели"))
        self.label_4.setText(_translate("MainWindow", "Альфа"))
        self.label_5.setText(_translate("MainWindow", "Вид регрессора"))
        self.cb_lnx.setText(_translate("MainWindow", "lnX"))
        self.cb_x2.setText(_translate("MainWindow", "x^2"))
        self.cb_1x.setText(_translate("MainWindow", "1/x"))
        self.cb_ex.setText(_translate("MainWindow", "e^x"))
        self.pb_build_model.setStyleSheet(_translate("MainWindow", "0"))
        self.pb_build_model.setText(_translate("MainWindow", "Построить модель"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action_open_file.setText(_translate("MainWindow", "Открыть"))
        self.action_export.setText(_translate("MainWindow", "Экспорт"))
        self.action_import.setText(_translate("MainWindow", "Импорт"))
